name: Node.js CI

on: [push]

jobs:
 build:
  runs-on: ubuntu-latest

  strategy:
   matrix:
    node-version: [10.x, 12.x]

  steps:
   - name: Checkout repository
     uses: actions/checkout@v2

   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
      node-version: ${{ matrix.node-version }}

   - name: Install Packages and build
     run: |
      npm install
      npm run build --if-present

   - name: Deploy to GH Pages
     run: |
      npm run deploy
